In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/all_nu_clubs.csv')

In [3]:
df.shape

(156, 104)

In [4]:
for i in df.columns:
    print(i)

id
name
type
category
email
recruitment_status
verified
recruitment_link
description
established
head
telegram_url
instagram_url
created_at
updated_at
head_user/sub
head_user/name
head_user/surname
head_user/picture
permissions/can_edit
permissions/can_delete
achievements/0/description
achievements/0/year
achievements/0/id
achievements/0/community_id
achievements/0/created_at
achievements/0/updated_at
achievements/1/description
achievements/1/year
achievements/1/id
achievements/1/community_id
achievements/1/created_at
achievements/1/updated_at
achievements/2/description
achievements/2/year
achievements/2/id
achievements/2/community_id
achievements/2/created_at
achievements/2/updated_at
achievements/3/description
achievements/3/year
achievements/3/id
achievements/3/community_id
achievements/3/created_at
achievements/3/updated_at
media/0/id
media/0/url
media/0/mime_type
media/0/entity_type
media/0/entity_id
media/0/media_format
media/0/media_order
media/1/id
media/1/url
media/1/mime_type
media/1/entity_type
media/1/entity_id
media/1/media_format
media/1/media_order
achievements/4/description
achievements/4/year
achievements/4/id
achievements/4/community_id
achievements/4/created_at
achievements/4/updated_at
achievements/5/description
achievements/5/year
achievements/5/id
achievements/5/community_id
achievements/5/created_at
achievements/5/updated_at
achievements/6/description
achievements/6/year
achievements/6/id
achievements/6/community_id
achievements/6/created_at
achievements/6/updated_at
achievements/7/description
achievements/7/year
achievements/7/id
achievements/7/community_id
achievements/7/created_at
achievements/7/updated_at
media/2/id
media/2/url
media/2/mime_type
media/2/entity_type
media/2/entity_id
media/2/media_format
media/2/media_order
media/3/id
media/3/url
media/3/mime_type
media/3/entity_type
media/3/entity_id
media/3/media_format
media/3/media_order
media/4/id
media/4/url
media/4/mime_type
media/4/entity_type
media/4/entity_id
media/4/media_format
media/4/media_order

In [5]:
df = df[df['type'] == 'club']
df

,id,name,type,category,email,recruitment_status,verified,recruitment_link,description,established,...,media/3/entity_id,media/3/media_format,media/3/media_order,media/4/id,media/4/url,media/4/mime_type,media/4/entity_type,media/4/entity_id,media/4/media_format,media/4/media_order
0,49,25th July Cinema,club,cultural,25july@nu.edu.kz,closed,True,https://docs.google.com/forms/d/e/1FAIpQLScf9r...,25th July Cinema Club is a collaborative hub f...,2020-09-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17,Accounting and Auditing Club,club,academic,aac@nu.edu.kz,closed,True,https://nu.edu.kz/clubs/aac/join,Accounting and Auditing Club (AAC) is a profes...,2020-09-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20,ACM@NU,club,academic,acmsc@nu.edu.kz,closed,True,https://forms.gle/h5cnGDpa9HQ5NLpR7,ACM@NU - the first and only branches of the in...,2017-02-04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,150,Acoustic Night Community,club,cultural,acousticnight@nu.edu.kz,closed,True,NaN,Acoustic Night has been a part of Nazarbayev U...,2025-10-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,63,Adventure Club,club,cultural,adventure.club@nu.edu.kz,closed,False,https://nu.edu.kz/clubs/adventure.club/join,Official Adventure Club at Nazarbayev University.,2020-09-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,110,Volunteers Club,club,social,volunteers@nu.edu.kz,closed,False,https://nu.edu.kz/clubs/volunteers/join,Our club brings all volunteers together to gai...,2020-09-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,4,Vox Club,club,academic,vox@nu.edu.kz,closed,True,https://www.google.com/,Our club avoided the COVID-19 crisis by commen...,2025-02-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,40,Women in Engineering (WEC),club,academic,wec@nu.edu.kz,closed,True,https://forms.gle/jSfuZxxrTkH9D2gVA,Women in Engineering (WEC) is a dynamic and su...,2020-01-30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,103,YBS Kpop Cover Dance Club,club,sports,kpopcdc@nu.edu.kz,closed,False,https://nu.edu.kz/clubs/kpopcdc/join,Our club specializes on K-Pop cover dance and ...,2020-09-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,130,МБОУ СОШ Community,club,social,adilet.akhat@nu.edu.kz,closed,False,https://forms.gle/yCubFRNXdwx51uds9,A home for students who came from regular publ...,2025-08-14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df = df[['id', 'name', 'category', 'email', 'description', 'established', 'telegram_url', 'instagram_url', ]]
df

,id,name,category,email,description,established,telegram_url,instagram_url
0,49,25th July Cinema,cultural,25july@nu.edu.kz,25th July Cinema Club is a collaborative hub f...,2020-09-01,https://t.me/CinemaJuly25th,https://www.instagram.com/xxv07/
1,17,Accounting and Auditing Club,academic,aac@nu.edu.kz,Accounting and Auditing Club (AAC) is a profes...,2020-09-01,https://t.me/nu__aac,https://www.instagram.com/nu__aac
2,20,ACM@NU,academic,acmsc@nu.edu.kz,ACM@NU - the first and only branches of the in...,2017-02-04,https://t.me/nuacmsc,https://www.instagram.com/nuacmsc/
3,150,Acoustic Night Community,cultural,acousticnight@nu.edu.kz,Acoustic Night has been a part of Nazarbayev U...,2025-10-19,NaN,https://www.instagram.com/acoustic.night/
4,63,Adventure Club,cultural,adventure.club@nu.edu.kz,Official Adventure Club at Nazarbayev University.,2020-09-01,https://t.me/adventure.club,https://www.instagram.com/adventure.club
...,...,...,...,...,...,...,...,...
151,110,Volunteers Club,social,volunteers@nu.edu.kz,Our club brings all volunteers together to gai...,2020-09-01,https://t.me/volunteers,https://www.instagram.com/volunteersclub/
152,4,Vox Club,academic,vox@nu.edu.kz,Our club avoided the COVID-19 crisis by commen...,2025-02-10,https://t.me,https://www.instagram.com/vox_phil_nu/
153,40,Women in Engineering (WEC),academic,wec@nu.edu.kz,Women in Engineering (WEC) is a dynamic and su...,2020-01-30,https://t.me/wec_ji,https://www.instagram.com/nu_wec/
154,103,YBS Kpop Cover Dance Club,sports,kpopcdc@nu.edu.kz,Our club specializes on K-Pop cover dance and ...,2020-09-01,https://t.me/kpopcdc,https://www.instagram.com/nu.ybs/
155,130,МБОУ СОШ Community,social,adilet.akhat@nu.edu.kz,A home for students who came from regular publ...,2025-08-14,NaN,NaN

In [8]:
df.to_csv('updated_clubs.csv')

In [9]:
df = df[~(df['id'] == 156)]

In [10]:
df = df[~(df['name'] in ['higgsfield enjoyers', 'SG Ministry of Culture', 'Ministry of Sports and Health', 'Ministry of External Affairs', 'NU Brainstorm', 'NU Cheerleading Club', 'NU Graduate Student Union', 'NU Motorsports', ''])]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().