In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../data/clubs_with_interest_areas.csv')

In [4]:
df.interest_areas.value_counts()

interest_areas
Sports & Fitness                                                         16
Culture & Languages                                                      12
Science & Research                                                       12
Debate & Public Speaking                                                  7
Business & Finance                                                        7
Technology & Computing                                                    6
Music & Performance                                                       6
Arts & Creativity                                                         5
Social Impact & Volunteering                                              4
Gaming & Esports                                                          4
Dance                                                                     4
Dance; Culture & Languages                                                4
Arts & Creativity; Culture & Languages                                    3
Technology & Computing; Science & Research                                3
Arts & Creativity; Film & Media                                           3
Science & Research; Technology & Computing                                2
Social Impact & Volunteering; Debate & Public Speaking                    2
Social Impact & Volunteering; Science & Research                          2
Film & Media; Arts & Creativity                                           2
Film & Media                                                              2
Arts & Creativity; Social Impact & Volunteering                           2
Technology & Computing; Gaming & Esports; Arts & Creativity               1
Social Impact & Volunteering; Arts & Creativity                           1
Culture & Languages; Social Impact & Volunteering                         1
Arts & Creativity; Music & Performance                                    1
Business & Finance; Culture & Languages; Social Impact & Volunteering     1
Technology & Computing; Gaming & Esports                                  1
Music & Performance; Culture & Languages                                  1
Science & Research; Film & Media                                          1
Science & Research; Social Impact & Volunteering                          1
Debate & Public Speaking; Science & Research                              1
Business & Finance; Social Impact & Volunteering                          1
Debate & Public Speaking; Social Impact & Volunteering                    1
Name: count, dtype: int64

In [6]:
interest_map = {"Sports & Fitness" : 1,
"Culture & Languages" : 2,
"Science & Research" : 3,
"Debate & Public Speaking" : 4,
"Business & Finance" : 5,
"Technology & Computing" : 6,
"Music & Performance" : 7,
"Arts & Creativity" : 8,
"Social Impact & Volunteering" : 9,
"Gaming & Esports" : 10,
"Dance" : 11,
"Film & Media" : 12 }

In [7]:
def map_interests(text):
    items = text.split('; ')
    return [interest_map[item] for item in items if item in interest_map]

df['interest_areas_ids'] = df['interest_areas'].apply(map_interests)

print(df[['interest_areas', 'interest_areas_ids']].head())

           interest_areas interest_areas_ids
0            Film & Media               [12]
1      Business & Finance                [5]
2  Technology & Computing                [6]
3     Music & Performance                [7]
4        Sports & Fitness                [1]

In [10]:
df

,Unnamed: 0.1,Unnamed: 0,id,name,category,email,established,telegram_url,instagram_url,description_clean,interest_areas,interest_areas_ids
0,0,0,49,25th July Cinema,cultural,25july@nu.edu.kz,2020-09-01,https://t.me/CinemaJuly25th,https://www.instagram.com/xxv07/,25th July Cinema Club is a collaborative hub f...,Film & Media,[12]
1,1,1,17,Accounting and Auditing Club,academic,aac@nu.edu.kz,2020-09-01,https://t.me/nu__aac,https://www.instagram.com/nu__aac,Accounting and Auditing Club (AAC) is a profes...,Business & Finance,[5]
2,2,2,20,ACM@NU,academic,acmsc@nu.edu.kz,2017-02-04,https://t.me/nuacmsc,https://www.instagram.com/nuacmsc/,ACM@NU -is the Nazarbayev University branch of...,Technology & Computing,[6]
3,3,3,150,Acoustic Night Community,cultural,acousticnight@nu.edu.kz,2025-10-19,https://t.me/acousticnightcommunity,https://www.instagram.com/acoustic.night/,Acoustic Night has been a part of Nazarbayev U...,Music & Performance,[7]
4,4,4,63,Adventure Club,cultural,adventure.club@nu.edu.kz,2020-09-01,https://t.me/adventure.club,https://www.instagram.com/adventure.club,Official Adventure Club at Nazarbayev Universi...,Sports & Fitness,[1]
...,...,...,...,...,...,...,...,...,...,...,...,...
115,115,150,95,Volleyball Club,sports,volleyballclub@nu.edu.kz,2020-09-01,https://t.me/nuvolleyballclub,https://www.instagram.com/nuvolleyballclub/,NUVC holds many tournaments among students wit...,Sports & Fitness,[1]
116,116,151,110,Volunteers Club,social,volunteers@nu.edu.kz,2020-09-01,https://t.me/volunteers,https://www.instagram.com/volunteersclub/,Our club brings all volunteers together to gai...,Social Impact & Volunteering,[9]
117,117,152,4,Vox Club,academic,vox@nu.edu.kz,2025-02-10,https://t.me,https://www.instagram.com/vox_phil_nu/,Our club avoided the COVID-19 crisis by commen...,Debate & Public Speaking,[4]
118,118,153,40,Women in Engineering (WEC),academic,wec@nu.edu.kz,2020-01-30,https://t.me/wec_ji,https://www.instagram.com/nu_wec/,Women in Engineering (WEC) is a dynamic and su...,Technology & Computing; Science & Research,"[6, 3]"
119,119,154,103,YBS Kpop Cover Dance Club,sports,kpopcdc@nu.edu.kz,2020-09-01,https://t.me/kpopcdc,https://www.instagram.com/nu.ybs/,Our club specializes on K-Pop cover dance and ...,Dance; Culture & Languages,"[11, 2]"

In [11]:
df = df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'])

In [12]:
df

,id,name,category,email,established,telegram_url,instagram_url,description_clean,interest_areas,interest_areas_ids
0,49,25th July Cinema,cultural,25july@nu.edu.kz,2020-09-01,https://t.me/CinemaJuly25th,https://www.instagram.com/xxv07/,25th July Cinema Club is a collaborative hub f...,Film & Media,[12]
1,17,Accounting and Auditing Club,academic,aac@nu.edu.kz,2020-09-01,https://t.me/nu__aac,https://www.instagram.com/nu__aac,Accounting and Auditing Club (AAC) is a profes...,Business & Finance,[5]
2,20,ACM@NU,academic,acmsc@nu.edu.kz,2017-02-04,https://t.me/nuacmsc,https://www.instagram.com/nuacmsc/,ACM@NU -is the Nazarbayev University branch of...,Technology & Computing,[6]
3,150,Acoustic Night Community,cultural,acousticnight@nu.edu.kz,2025-10-19,https://t.me/acousticnightcommunity,https://www.instagram.com/acoustic.night/,Acoustic Night has been a part of Nazarbayev U...,Music & Performance,[7]
4,63,Adventure Club,cultural,adventure.club@nu.edu.kz,2020-09-01,https://t.me/adventure.club,https://www.instagram.com/adventure.club,Official Adventure Club at Nazarbayev Universi...,Sports & Fitness,[1]
...,...,...,...,...,...,...,...,...,...,...
115,95,Volleyball Club,sports,volleyballclub@nu.edu.kz,2020-09-01,https://t.me/nuvolleyballclub,https://www.instagram.com/nuvolleyballclub/,NUVC holds many tournaments among students wit...,Sports & Fitness,[1]
116,110,Volunteers Club,social,volunteers@nu.edu.kz,2020-09-01,https://t.me/volunteers,https://www.instagram.com/volunteersclub/,Our club brings all volunteers together to gai...,Social Impact & Volunteering,[9]
117,4,Vox Club,academic,vox@nu.edu.kz,2025-02-10,https://t.me,https://www.instagram.com/vox_phil_nu/,Our club avoided the COVID-19 crisis by commen...,Debate & Public Speaking,[4]
118,40,Women in Engineering (WEC),academic,wec@nu.edu.kz,2020-01-30,https://t.me/wec_ji,https://www.instagram.com/nu_wec/,Women in Engineering (WEC) is a dynamic and su...,Technology & Computing; Science & Research,"[6, 3]"
119,103,YBS Kpop Cover Dance Club,sports,kpopcdc@nu.edu.kz,2020-09-01,https://t.me/kpopcdc,https://www.instagram.com/nu.ybs/,Our club specializes on K-Pop cover dance and ...,Dance; Culture & Languages,"[11, 2]"

In [13]:
df.to_csv('../data/clubs_with_interest_areas.csv', index=False)